### PR TITLE
[Structure] Story Templates: Renames template directories

### PR DESCRIPTION
**Pull request by divyarajmasani**
To accommodate the increasing number of templates, we may consider restructuring how the templates are loaded.

Addresses #468 

- Renames vertical based directories for raw templates and stickers, to use title from the first page of the story template.
- Updates media asset paths to use new changes introduced in #504 
- Updates templates package tests for new changes.

### CODE REVIEW

**Comment by swissspidy** [comment]
👍 on moving each template file to its own directory for now, but I'd move them to `packages/templates/src/raw/fresh-and-bright/index.js`, not `packages/templates/src/raw/fresh-and-bright/index.js`

We could explain the verticals in `packages/templates/README.md` if needed

**Comment by divyarajmasani** [comment]
@swissspidy , In this PR I've updated to directly use the story template name, and moved following templates,

- beauty -> fresh-and-bright
- cooking -> food-and-stuff
- diy -> doers-get-more-done
- entertainment -> weekly-entertainment

Moves stickers and raw template to appropriate directories, now there are 4 more core templates remaining to move to this structure.

I wanted to get your view on this, if I should go ahead and move all current 8 templates as discussed? And also raise a companion PR for static-asset to updated the names.

I believe getting this merged will help working and raising PRs for the rest of the batches. let me know your thoughts.

Or we would like [#7196](https://github.com/google/web-stories-wp/issues/7196) to get addressed first before making any commits for new templates?

**Comment by swissspidy** [comment]
> I wanted to get your view on this, if I should go ahead and move all current 8 templates as discussed? And also raise a companion PR for static-asset to updated the names.
> 
> I believe getting this merged will help working and raising PRs for the rest of the batches. let me know your thoughts.

Sounds good, let's go ahead with this.

> Or we would like [#7196](https://github.com/google/web-stories-wp/issues/7196) to get addressed first before making any commits for new templates?

I haven't started work on #7196 yet and I don't want to make it a blocker. Feel free to proceed without it :-)

**Review by swissspidy — APPROVED** [review]

**Comment by divyarajmasani** [comment]
Closing this, as the changes have been merged in main.

> https://github.com/google/web-stories-wp/pull/7697

**Pull request closed without merging**
