### PR TITLE
[Structure] Moves core template assets to new proposed directories

### PR DESCRIPTION
**Pull request by divyarajmasani**
## Context

Now that new story templates are in making, existing files for the raw templates and the stickers required re-structuring to accommodate new templates logically. 

This PR extends the same proposed structure to move template specific files to a new directory with name taken from the first page of the story template.

## Summary

Renames template directories to match that of the title on the first page of the story template. And removes vertical prefixes from the assets.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by divyarajmasani** [comment]
@swissspidy 

I'm not sure how we can test these file changes, or if, once merged into main ( google repo ), it will have any user facing issues.

I believe there are separate directories for each release of the version, if I'm not wrong, so merging this to main won't be an issue.

Or are the assets served from the `main/` itself and we need to keep the older paths intact?

**Comment by swissspidy** [comment]
> @swissspidy
> 
> I'm not sure how we can test these file changes, or if, once merged into main ( google repo ), it will have any user facing issues.
> 
> I believe there are separate directories for each release of the version, if I'm not wrong, so merging this to main won't be an issue.
> 
> Or are the assets served from the `main/` itself and we need to keep the older paths intact?

Correct, each release uses separate directories. `main` is only used for development builds, i.e. if you are running it from GitHub ([see docs](https://github.com/google/web-stories-wp/blob/main/docs/cdn.md#usage-in-the-plugin))

Change here looks good 👍

**Comment by divyarajmasani** [comment]
Perfect, then I shall raise the PRs on the main ( Google ) repo.

**Comment by divyarajmasani** [comment]
Closing this as the changes have been merged.
> https://github.com/google/web-stories-wp/pull/7695

**Pull request closed without merging**
